### ISSUE TITLE
Unable to use `teamsfx account login azure` in teamsfx-cli 2.1.0 but succeeds in 2.0.2

### ISSUE THREAD

**Issue by ottD** [OfficeDev/TeamsFx#10567]
**Describe the bug**

When running `npx teamsfx account login azure --service-principal --username xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --password *** --tenant xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` in an Azure DevOps pipeline I get the following error message when using `teamsfx-cli 2.1.0 `but the exact same command works fine when using version `2.0.2` of `teamsfx-cli`. 

```
(✖) Error: unknown.UnhandledError: An unexpected error has occurred while performing the unknown task. 
{"stack":"Error: UsernamePasswordCredential: tenantId, clientId, username and password are required parameters. To troubleshoot, visit [https://aka.ms/azsdk/js/identity/usernamepasswordcredential/troubleshoot.\n](https://aka.ms/azsdk/js/identity/usernamepasswordcredential/troubleshoot./n)    
at new UsernamePasswordCredential (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:2029698)\n    
at AzureAccountProviderUserPassword.<anonymous> (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:4037035)
at Generator.next (<anonymous>)
at /home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:4035439\n    
at new Promise (<anonymous>)\n   
at __awaiter (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:4034987)\n    
at AzureAccountProviderUserPassword.getIdentityCredentialAsync (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:4036909)\n    
at AzureAccountProviderUserPassword.<anonymous> (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:4037865)\n   
at Generator.next (<anonymous>)\n    
at /home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:4035439\n   
at new Promise (<anonymous>)\n   
at __awaiter (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:4034987)\n   
at AzureAccountProviderUserPassword.getJsonObject (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:4037797)\n    
at AccountUtils.<anonymous> (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:3936651)\n    
at Generator.next (<anonymous>)\n   
at fulfilled (/home/vsts/work/1/s/node_modules/@microsoft/teamsfx-cli/lib/index.js:14:3934176)","message":"UsernamePasswordCredential: tenantId, clientId, username and password are required parameters. To troubleshoot, visit [https://aka.ms/azsdk/js/identity/usernamepasswordcredential/troubleshoot."}](https://aka.ms/azsdk/js/identity/usernamepasswordcredential/troubleshoot.%22%7D)
 ```

**To Reproduce**
1. In your Teams project, setup an Azure DevOps that uses below task for building and deploying: 
```yaml
 - task: Bash@3
    displayName: "Build and deploy Teams project"
    env:
      # To enable M365 account login by environment variables and non-interactive mode.
      CI_ENABLED: "true"
      # To specify the environment name which will be used as an option below.
      # You can change it to use your own environment name.
      TEAMSFX_ENV_NAME: "dev"
      # To specify the version of TTK CLI for use.
      TEAMSFX_CLI_VERSION: 2.*
    inputs:
      targetType: "inline"
      script: |
        set -evuxo pipefail

        # Install the TTK CLI for later use.
        npm install @microsoft/teamsfx-cli@${TEAMSFX_CLI_VERSION}

        # Build the project.
        npm install
        npm run build

        # deployment steps
        # Login Azure by service principal
        npx teamsfx account login azure --service-principal --username $(AZURE_SERVICE_PRINCIPAL_NAME) --password $(AZURE_SERVICE_PRINCIPAL_PASSWORD) --tenant $(AZURE_TENANT_ID)

        # Deploy to hosting environment.
        npx teamsfx deploy --env ${TEAMSFX_ENV_NAME}
```

2.  Observe how the `npx teamsfx account login azure` step fails with `Error: UsernamePasswordCredential: tenantId, clientId, username and password are required parameters.`
3. Set the `TEAMSFX_CLI_VERSION` parameter to `2.0.2` instead of `2.*` and re-run the pipeline
4. Observe how the `npx teamsfx account login azure` step succeeds without error.

**Expected behavior**
I would expect the `teamsfx account login azure` command to work as described in the [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-cli?pivots=version-one#teamsfx-account-1). I can't find any documented breaking change between version `2.0.2` and `2.1.0` that would suggest the `teamsfx account login azure` command is no longer supported in `2.1.0`. Please advise. 

**Screenshots**

<img width="1211" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/33263347/9d08e6a8-81d9-4228-b728-bd1e4cb16a72">

**CLI Information**
 - OS: Ubuntu
 - Version 22.04.3 LTS
