### ISSUE TITLE
bug report: arm/deploy.UnhandledError

### ISSUE THREAD

**Issue by theodury** [OfficeDev/TeamsFx#10902]
Cannot redefine property: stack

stack:
UnhandledError: Cannot redefine property: stack
    at getError (<REDACTED: user-file-path>:14:6313245)
    at Object.wrapRun (<REDACTED: user-file-path>:14:6313423)
    at processTicksAndRejections (node:<REDACTED: user-file-path>:95:5)
    at ArmDeployDriver.execute (<REDACTED: user-file-path>:14:6056370)
    at Lifecycle.executeImpl (<REDACTED: user-file-path>:14:5935227)
    at Lifecycle.execute (<REDACTED: user-file-path>:14:5932384)
    at Coordinator.provision (<REDACTED: user-file-path>:14:5976180)
    at Coordinator.<anonymous> (<REDACTED: user-file-path>:14:6600016)
    at FxCore.provisionResources (<REDACTED: user-file-path>:14:6529125)
    at FxCore.exports.EnvWriterMW (<REDACTED: user-file-path>:14:6441982)
    at FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path>:14:6603768)
    at FxCore.exports.ConcurrentLockerMW (<REDACTED: user-file-path>:14:6602719)
    at envLoaderMWImpl (<REDACTED: user-file-path>:14:6441929)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:14:6440843)
    at FxCore.exports.ProjectMigratorMWV3 (<REDACTED: user-file-path>:14:6634319)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>:14:6604265)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:14:6600016)

**Comment by andremarques023** [comment]
We are facing the same issue.

**Comment by italogoncalvessilveira** [comment]
Same error here

**Comment by chandanpjain** [comment]
Facing same error when trying the sample python conversation bot.

**Comment by jayzhang** [comment]
@theodury Thanks for feedback. We will fix it.

**Comment by theodury** [comment]
@jayzhang  Ok if you need anymore detail i will be welcome to have a call with you if necessary: 

I was thinking that was an authorization issue : 

![image](https://github.com/OfficeDev/TeamsFx/assets/6726393/d7f2fdfe-63de-4676-a461-172a1b0b06ec)

![image](https://github.com/OfficeDev/TeamsFx/assets/6726393/064674cf-ea70-4400-872b-a4ca852089ea)

**Comment by theodury** [comment]
@jayzhang By the way i did comment this line because of this issue : 

![image](https://github.com/OfficeDev/TeamsFx/assets/6726393/9bd57591-c01a-48ae-a2b8-9c9eb627af2d)

![image](https://github.com/OfficeDev/TeamsFx/assets/6726393/44cfbc7d-6cb1-489f-8e2a-e1e7d6ff3b85)


```

# yaml-language-server: $schema=https://aka.ms/teams-toolkit/1.0.0/yaml.schema.json
# Visit https://aka.ms/teamsfx-v5.0-guide for details on this file
# Visit https://aka.ms/teamsfx-actions for details on actions
version: 1.0.0

environmentFolderPath: ./env

# Triggered when 'teamsfx provision' is executed
provision:
  - uses: teamsApp/create # Creates a Teams app
    with:
      name: TeamsChef-${{TEAMSFX_ENV}} # Teams app name
    writeToEnvironmentFile:
      # Write the information of installed dependencies into environment file for the specified environment variable(s).
      teamsAppId: TEAMS_APP_ID

  - uses: botAadApp/create # Creates a new AAD app for Bot Registration.
    with:
      name: TeamsChef
    writeToEnvironmentFile:
      botId: BOT_ID
      botPassword: SECRET_BOT_PASSWORD

  - uses: arm/deploy # Deploy given ARM templates parallelly.
    with:
      subscriptionId: ${{AZURE_SUBSCRIPTION_ID}} # The AZURE_SUBSCRIPTION_ID is a built-in environment variable. TeamsFx will ask you select one subscription if its value is empty. You're free to reference other environment varialbe here, but TeamsFx will not ask you to select subscription if it's empty in this case.
      resourceGroupName: ${{AZURE_RESOURCE_GROUP_NAME}} # The AZURE_RESOURCE_GROUP_NAME is a built-in environment variable. TeamsFx will ask you to select or create one resource group if its value is empty. You're free to reference other environment varialbe here, but TeamsFx will not ask you to select or create resource grouop if it's empty in this case.
      templates:
        - path: ./infra/azure.bicep
          parameters: ./infra/azure.parameters.json
          deploymentName: Create-resources-for-bot
      bicepCliVersion: v0.9.1 # Teams Toolkit will download this bicep CLI version from github for you, will use bicep CLI in PATH if you remove this config.
    # Output: every bicep output will be persisted in current environment's .env file with certain naming conversion. Refer https://aka.ms/teamsfx-actions/arm-deploy for more details on the naming conversion rule.

  - uses: teamsApp/validateManifest # Validate using manifest schema
    with:
      manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
  - uses: teamsApp/zipAppPackage # Build Teams app package with latest env value
    with:
      manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
      outputZipPath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
      outputJsonPath: ./build/teamsAppManifest/manifest.${{TEAMSFX_ENV}}.json
  - uses: teamsApp/update # Apply the Teams app manifest to an existing Teams app in Teams Developer Portal. Will use the app id in manifest file to determine which Teams app to update.
    with:
      appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip # Relative path to this file. This is the path for built zip file.
    # writeToEnvironmentFile:
    #   # Write the information of installed dependencies into environment file for the specified environment variable(s).
    #   teamsAppId: TEAMS_APP_ID

# Triggered when 'teamsfx deploy' is executed
# deploy:
#   - uses: azureAppService/deploy # Deploy bits to Azure App Serivce
#     with:
#       distributionPath: . # Deploy base folder
#       ignoreFile: ./.appserviceignore # Can be changed to any ignore file location, leave blank will ignore nothing
#       resourceId: ${{BOT_AZURE_APP_SERVICE_RESOURCE_ID}} # The resource id of the cloud resource to be deployed to. This key will be generated by arm/deploy action automatically. You can replace it with your existing Azure Resource id or add it to your environment variable file.

# Triggered when 'teamsfx publish' is executed
publish:
  - uses: teamsApp/validateManifest # Validate using manifest schema
    with:
      manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
  - uses: teamsApp/zipAppPackage
    with:
      manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
      outputZipPath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
      outputJsonPath: ./build/teamsAppManifest/manifest.${{TEAMSFX_ENV}}.json
  - uses: teamsApp/update # Apply the Teams app manifest to an existing Teams app in Teams Developer Portal. Will use the app id in manifest file to determine which Teams app to update.
    with:
      appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip # Relative path to this file. This is the path for built zip file.
    # writeToEnvironmentFile:
    #   # Write the information of installed dependencies into environment file for the specified environment variable(s).
    #   teamsAppId: TEAMS_APP_ID
  - uses: teamsApp/publishAppPackage # Publish the app to Teams Admin Center (https://admin.teams.microsoft.com/policies/manage-apps) for review and approval
    with:
      appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
    writeToEnvironmentFile:
      # Write the information of installed dependencies into environment file for the specified environment variable(s).
      publishedAppId: TEAMS_APP_PUBLISHED_APP_ID
projectId: dc566bd8-248c-4295-8b72-9220810ffb6c
```
