### ISSUE TITLE
Bicep failure returns success in Azure DevOps

### ISSUE THREAD

**Issue by AvinZarlez** [OfficeDev/TeamsFx#11141]
**Description**

When running TeamsFX Provision as a CLI step in an Azure Pipeline, the command returns success if the teamsfx pipeline runs. However, if the `arm/deploy` step's bicep deployment fails, this failure is not captured and the command still returns success. This causes the pipeline to run "Green" in Azure DevOps even if the bicep failed to deploy.

**To Reproduce**
1. Create a `teamsapp.yml` pipeline that includes a `arm/deploy` bicep step.
2. Create an Azure DevOps provision pipeline with the following yml:
```yaml
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: TEAMSFX_ENV_NAME
    displayName: Team Environment
    type: string
    default: "dev"
  - name: deployGroupSelection
    displayName: Deployment Variable Group Selection
    type: string
    default: "deploy-variables"

variables:
  - name: TEAMS_PATH
    value: $(System.DefaultWorkingDirectory)/teams
  - group: ${{ parameters.deployGroupSelection }}

steps:
  # Setup environment.
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
      checkLatest: true

  # Check out
  - checkout: self
    clean: true
    persistCredentials: true

  - task: Bash@3
    displayName: "Install Teamsfx"
    env:
      # To specify the version of TTK CLI for use.
      TEAMSFX_CLI_VERSION: 2.*
    inputs:
      workingDirectory: $(TEAMS_PATH)
      targetType: "inline"
      script: |
        set -evuxo pipefail

        # Install the TTK CLI for later use.
        npm install @microsoft/teamsfx-cli@${TEAMSFX_CLI_VERSION}

  - task: AzureCLI@2
    displayName: "Provision"
    env:
      M365_ACCOUNT_NAME: $(M365_ACCOUNT_NAME)
      M365_ACCOUNT_PASSWORD: $(M365_ACCOUNT_PASSWORD)
      M365_TENANT_ID: $(M365_TENANT_ID)
      AZURE_RESOURCE_GROUP_NAME: $(AZURE_RESOURCE_GROUP_NAME) # Only needs to be set for first provision, setting just in case.
      CI_ENABLED: "true"
    inputs:
      workingDirectory: $(TEAMS_PATH)
      azureSubscription: "$(AZURE_SERVICE_CONNECTION)"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        set -evuxo pipefail

        npx teamsfx account login azure --service-principal --username $servicePrincipalId --password $servicePrincipalKey --tenant $tenantId --interactive false

        echo "Logged in. Now will provision"

        # After provisioning, you should commit necessary files under teamsfx into the repository.

        export AZURE_SUBSCRIPTION_ID=$(az account show --query id --output tsv)

        npx teamsfx provision --env ${{ parameters.TEAMSFX_ENV_NAME }}

  - task: Bash@3
    displayName: "Commit Changes"
    inputs:
      targetType: "inline"
      script: |
        # Commit provision configs if necessary.
        # To enable scripts to run git commands, check https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
        git config user.name "azdo-agent"
        git config user.email "azdo-agent@azure.com"

        git status

        git add .
        git commit -m "chore: commit provision configs"
        git push origin HEAD:${BUILD_SOURCEBRANCH}

        git status
```
(Based on this example: https://github.com/OfficeDev/TeamsFx/blob/2f5decfcc7452aad8b471fa1938cac800da7befa/docs/cicd/azdo/provision.azure.yml )
4. Run the pipeline with something changed on the Azure resource that causes the bicep deployment to fail
5. Pipeline logs show error, however the overall Azure task returns green.

**Expected behavior**
I expect the npx teamsfx provision command to return failure if the bicep deployment has errors.

**CLI Information (please complete the following information):**
 - OS: ubuntu (using Microsoft DevOps agent `ubuntu-latest`)
 - Version 2.1.1
 
**Additional context**
Ran into this issue on a customer project where the bicep started failing and it was not noticed since had to dig into the logs of whatever good looking runs to find the errors.

**Comment by jayzhang** [comment]
@AvinZarlez  Thanks for reporting, we are investigating this issue.

**Comment by jayzhang** [comment]
@AvinZarlez  We found this is a bug for CLI v2, could please upgrade CLI v3 and retry: 
```
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: TEAMSFX_ENV_NAME
    displayName: Team Environment
    type: string
    default: "dev"
  - name: deployGroupSelection
    displayName: Deployment Variable Group Selection
    type: string
    default: "deploy-variables"

variables:
  - name: TEAMS_PATH
    value: $(System.DefaultWorkingDirectory)/teams
  - group: ${{ parameters.deployGroupSelection }}

steps:
  # Setup environment.
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
      checkLatest: true

  # Check out
  - checkout: self
    clean: true
    persistCredentials: true

  - task: Bash@3
    displayName: "Install Teamsfx"
    env:
      # To specify the version of TTK CLI for use.
      TEAMSFX_CLI_VERSION: 3.*
    inputs:
      workingDirectory: $(TEAMS_PATH)
      targetType: "inline"
      script: |
        set -evuxo pipefail

        # Install the TTK CLI for later use.
        npm install @microsoft/teamsapp-cli@${TEAMSFX_CLI_VERSION}

  - task: AzureCLI@2
    displayName: "Provision"
    env:
      M365_ACCOUNT_NAME: $(M365_ACCOUNT_NAME)
      M365_ACCOUNT_PASSWORD: $(M365_ACCOUNT_PASSWORD)
      M365_TENANT_ID: $(M365_TENANT_ID)
      AZURE_RESOURCE_GROUP_NAME: $(AZURE_RESOURCE_GROUP_NAME) # Only needs to be set for first provision, setting just in case.
      CI_ENABLED: "true"
    inputs:
      workingDirectory: $(TEAMS_PATH)
      azureSubscription: "$(AZURE_SERVICE_CONNECTION)"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        set -evuxo pipefail

        npx teamsapp account login azure --service-principal --username $servicePrincipalId --password $servicePrincipalKey --tenant $tenantId --interactive false

        echo "Logged in. Now will provision"

        # After provisioning, you should commit necessary files under teamsapp into the repository.

        export AZURE_SUBSCRIPTION_ID=$(az account show --query id --output tsv)

        npx teamsapp provision --env ${{ parameters.TEAMSFX_ENV_NAME }}

  - task: Bash@3
    displayName: "Commit Changes"
    inputs:
      targetType: "inline"
      script: |
        # Commit provision configs if necessary.
        # To enable scripts to run git commands, check https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
        git config user.name "azdo-agent"
        git config user.email "azdo-agent@azure.com"

        git status

        git add .
        git commit -m "chore: commit provision configs"
        git push origin HEAD:${BUILD_SOURCEBRANCH}

        git status
```
