### ISSUE TITLE
Unable to publish the version from the teamsapp-cli

### ISSUE THREAD

**Issue by tbhaxor** [OfficeDev/TeamsFx#11249]
**Describe the bug**

I want to publish the teams application from the [`@microsoft/teamsapp-cli`](https://www.npmjs.com/package/@microsoft/teamsapp-cli). I can see `teamsApp/update` is working fine but `teamsApp/publishAppPackage` from the same provision lifecycle configuration is giving me the error. Unfortunately (even with `--verbose` and `--debug`), this is all I am getting on the console.
```
AppStudioPlugin.TeamsAppPublishFailed: Unable to publish Teams app with ID APP_GUID .Request path: POST /emea/api/publishing/f99fd0c1-6340-48ff-a99e-2f542c84b4f1/appdefinitions?teamstoolkit=true
```

**To Reproduce**
1. Install latest version (`npm i -g @microsoft/teamsapp-cli`)
2. Login the teamsapp-cli (`teamsapp account login m365`)
3. Build the application (`teamsapp provision --env prod && teamsapp deploy --env prod`)
4. Publish the application (`teamsapp publish --env prod`)

**Expected behavior**

It should work, as `teamsApp/update` is working. I can also confirm that Publish from the web ui ([https://dev.teams.microsoft.com/apps/${APP_ID}/overview](https://dev.teams.microsoft.com/apps/$%7BAPP_ID%7D/overview)) is working.

![image](https://github.com/OfficeDev/TeamsFx/assets/28386721/5a9f6438-2c61-4376-a3e8-d03a88d41789)

And I can confirm the application (v1.1.0) was submitted for approval, and is now approved.

![image](https://github.com/OfficeDev/TeamsFx/assets/28386721/0ccf7325-6739-4ae2-bffe-6b37dccdc54a)

**VS Code Extension Information (please complete the following information):**
N/A

**CLI Information (please complete the following information):**
 - OS: Windows 
 - Version: 11 (Build 22631.3374)

**Additional context**

Lifecycle hook configuration from `teamsapp.yaml`

```yaml
publish:
  - uses: teamsApp/update
    with:
      # Relative path to this file. This is the path for built zip file.
      appPackagePath: ./appPackage/build/appPackage.${{TEAMSFX_ENV}}.zip
  - uses: teamsApp/publishAppPackage
    with:
      appPackagePath: ./appPackage/build/appPackage.${{TEAMSFX_ENV}}.zip
    writeToEnvironmentFile:
      publishedAppId: TEAMS_APP_PUBLISHED_APP_ID
```
