### ISSUE TITLE
Creating a new bot with BOT PASSWORD not adding the bot password and get page 'NOT FOUND' error.

### ISSUE THREAD

**Issue by mrsci99** [OfficeDev/TeamsFx#13076]
Started in Teams Tools with the Create New App Basic Bot. This provisioned and deployed correctly and ran in Teams.

I then tried to switch the bot to multi tenant. I changed the teamsapp.yml to that shown below with a step using botAadApp/create.

This however doesn't create a password for the bot and when I click on the link 'Manage Password' next to the App Id in the Bot configuration page I get a page : Not Found.

Please explain/resolve.

----------------

see comment below for code

----------------

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 11

**CLI Information (please complete the following information):**

**Additional context**

**Comment by mrsci99** [comment]
I am able to manually create an app registation with password in Azure

**Comment by mrsci99** [comment]
```

# yaml-language-server: $schema=https://aka.ms/teams-toolkit/1.0.0/yaml.schema.json
# Visit https://aka.ms/teamsfx-v5.0-guide for details on this file
# Visit https://aka.ms/teamsfx-actions for details on actions
version: 1.0.0
environmentFolderPath: ./env

# Triggered when 'teamsapp provision' is executed
provision:
  # Automates the creation of a Teams app registration and saves the App ID to an environment file.
  - uses: teamsApp/create
    with:
      # Teams app name
      name: BOT3${{APP_NAME_SUFFIX}}
    # Write the information of created resources into environment file for
    # the specified environment variable(s).
    writeToEnvironmentFile:
      teamsAppId: TEAMS_APP_ID
  # Automates the creation an Azure AD app registration which is required for a bot.
  # The Bot ID (AAD app client ID) and Bot Password (AAD app client secret) are saved to an environment file.
  - uses: botAadApp/create
    with:
      name: BOT3${{APP_NAME_SUFFIX}}
    writeToEnvironmentFile:
      botId: BOT_ID
      botPassword: SECRET_BOT_PASSWORD

  # Create or update the bot registration on dev.botframework.com
  #- uses: botFramework/create
  #  with:
  #    botId: ${{BOT_ID}}
  #    name: BOT3
  #    messagingEndpoint: ${{BOT_ENDPOINT}}${{BOT_APP_PATH}}/api/messages
  #    description: ""
  #    channels:
  #      - name: msteams

```
