### ISSUE TITLE
Cipher text is broken error when using script action with powershell

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/TeamsFx#9315]
**Describe the bug**
```
DecryptionError: Cipher text is broken
    at LocalCrypto.decrypt (c:\Users\johmil\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.1\out\src\extension.js:2:7913120)
    at EnvUtil.readEnv (c:\Users\johmil\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.1\out\src\extension.js:2:7801548)
    at Object.exports.envLoaderMWImpl (c:\Users\johmil\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.1\out\src\extension.js:2:7120283)
    at FxCoreV3Implement.<anonymous> (c:\Users\johmil\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.1\out\src\extension.js:2:7118953)
    at FxCoreV3Implement.<anonymous> (c:\Users\johmil\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.1\out\src\extension.js:2:7123072)
    at FxCoreV3Implement.exports.ProjectMigratorMWV3 (c:\Users\johmil\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.1\out\src\extension.js:2:8067588)
    at FxCoreV3Implement.exports.ErrorHandlerMW (c:\Users\johmil\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.1\out\src\extension.js:2:7989320)
    at FxCoreV3Implement.dispatch (c:\Users\johmil\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.0.1\out\src\extension.js:2:7862596)
```

**To Reproduce**
I added an action to my Provision step to run a powershell script and it created this error:

```
  # Use a custom script copy TeamsFx env vars to AZD env files
  - uses: script
    with:
      shell: powershell
      run: "\"./copyforazd.ps1\" -env \"${{TEAMSFX_ENV}}\""
```
