### ISSUE TITLE
bug report: botAadApp create encrypting botPassword multiple times

### ISSUE THREAD

**Issue by Mikunj** [OfficeDev/TeamsFx#9780]
**Describe the bug**
Running `botAadApp/create` action will encrypt the existing secret if it exists.

**To Reproduce**

```yml
# yaml-language-server: $schema=https://aka.ms/teams-toolkit/1.0.0/yaml.schema.json
version: 1.0.0

environmentFolderPath: ./env

provision:
  - uses: botAadApp/create
    with:
      name: my-bot-name
    writeToEnvironmentFile:
      botId: MS_BOT_ID
      botPassword: SECRET_MS_BOT_SECRET
```

1. Run provision using the configuration above
2. Take note of `SECRET_MS_BOT_SECRET` value in user file
3. Run provision again
4. `SECRET_MS_BOT_SECRET` will be a completely different value from previous run and it will be a longer string

Decrypting `SECRET_MS_BOT_SECRET` from step 4 will yield you `SECRET_MS_BOT_SECRET` from step 2, which in turn being decrypted will yield the original secret.

**Expected behavior**
`botPassword` should only ever be encrypted once. Decrypting this should yield the secret instead of another encrypted string.

**CLI Information:**
 - OS: Ventura 13.5
 - Version 2.0.1
