### ISSUE TITLE
Can we get siteEndpoint in our code (v4)

### ISSUE THREAD

**Issue by sunshineo** [OfficeDev/TeamsFx#9792]
For our prod environment, it is fixed after deploy so we were able to copy it, but for the local development, it is a dynamic ngrok url. How can we get that value in our code?
I see getBotSiteEndpoint here in some test code that parses the config file, is that the only way?

**Comment by XiaofuHuang** [comment]
In Teams Toolkit V4, you can obtain the dynamic ngrok URL either by accessing the ngrok web interface [(sample code)](https://github.com/OfficeDev/TeamsFx/blob/ms-teams-vscode-extension%404.2.5/packages/fx-core/src/component/debug/util/ngrok.ts) or retrieving it from the `.fx\states\state.local.json` file.

In Teams Toolkit V5, it's possible to modify the `teamsapp.local.yml` file and include the `BOT_ENDPOINT` within the runtime environment variables.
```yaml
...
deploy:
  ...
  - uses: file/createOrUpdateEnvironmentFile
    with:
      target: ./.localConfigs
      envs:
        BOT_ID: ${{BOT_ID}}
        BOT_PASSWORD: ${{SECRET_BOT_PASSWORD}}
        BOT_ENDPOINT: ${{BOT_ENDPOINT}}
```
